# Generated by Django 2.2.1 on 2019-09-20 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tutorial.main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_numb', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('str_id', models.CharField(default='', editable=False, max_length=20, unique=True)),
                ('creation_date', models.DateField(default=datetime.date.today, editable=False)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.School', validators=[tutorial.main.models.validate_school_not_full])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
